export const api = {
  ProfilePicture: '/',
  AuthAppsLogin: '/login',
  AddDeviceInfo: '/devices/add-device',
  UpdateDeviceInfo: '/devices/inactive-device',
  Users: '/users',
  Messages: '/messages',
  ReceivedMessages: '/messages/received/',
  SentMessages: '/messages/sent/',
  DraftMessages: '/messages/draft/',
  RecycleBinMessages: '/messages/recyclebin/',
  totalReceived: '/messages/total-received/',
  totalSent: '/messages/total-sent/',
  totalDraft: '/messages/total-draft/',
  totalRecycleBin: '/messages/total-recyclebin/',
  Notifications: '/messages/notification/',
  UpdateReaders: '/messages/update-readers/',
  ReplyMessages: '/messages/reply/',
  DeleteMessage: '/messages/set-user-into-recyclebin/',
  DeleteFromRecycle: '/messages/remove-user-from-recyclebin/',
  MoveMultipleToRecycleBin: 'messages/move-multiple-to-recyclebin/',
  MoveMultipleFromRecycleBin: 'messages/move-multiple-from-recyclebin/',
  RegisterToken: '/push-notification/register-token',
  UnregisterToken: '/push-notification/unregister-token',
  SendNotification: '/push-notification/send-notification',
};
